{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "MyCo API Docs",
    "description": "Documentación oficial de la API REST de MyCo"
  },
  "host": "localhost:8001",
  "basePath": "/",f
  "tags": [
    {
      "name": "Residency",
      "description": "Endpoints relacionados con las residencias"
    },
    {
      "name": "Resident",
      "description": "Endpoints relacionados con las residentes"
    },
    {
      "name": "Bills",
      "description": "Endpoints relacionados con las facturas"
    },
    {
      "name": "Posts",
      "description": "Endpoints relacionas a las publicaciones"
    },
    {
      "name": "PropertyType",
      "description": "Endpoints relacionados con los tipos de propiedades de las residencias"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/residency/property-types": {
      "parameters": [
        {
          "name": "residency_id",
          "in": "body",
          "required": true,
          "description": "id de la residencia de la cual queremos obtener todos los tipos de propiedades",
          "type": "string",
          "example": {
            "residency_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
          }
        }
      ],
      "get": {
        "tags": [
          "PropertyType"
        ],
        "summary": "Obtener todos los tipos de propiedades dado un residency_id",
        "responses": {
          "200": {
            "example": [
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b",
                "residency_id": "e1ac73f8-c39e6bbd523acc4b-b047-46bc",
                "name": "Penthouse"
              },
              {
                "id": "6bbd523acc4a-b047-46bc-c39e-",
                "residency_id": "e1ac73f8-c39e6bbe1ac73f8-b047-lkj9",
                "name": "House with terrace"
              }
            ]
          }
        }
      },
      "post": {
        "tags": [
          "PropertyType"
        ],
        "summary": "Crear un nuevo tipo de propiedad dentro de una residencia",
        "responses": {
          "200": {
            "example": "Property type saved succesfully"
          }
        }
      },
      "put": {
        "tags": [
          "PropertyType"
        ],
        "summary": "Actualizar el nombre de un tipo de propiedad de una residencia (el único campo actualizable es el nombre)",
        "responses": {
          "200": {
            "example": "Property type updated succesfully"
          }
        }
      },
      "delete": {
        "tags": [
          "PropertyType"
        ],
        "summary": "Eliminar un tipo de propiedad de una residencia",
        "responses": {
          "200": {
            "example": "Property type removed succesfully"
          }
        }
      }
    },
    "/residency/bills": {
      "get":{
        "parameters": [
          {
            "name": "property_id",
            "in": "body",
            "required": true,
            "description": "id de la propiedad de la cual queremos obtener todas las facturas",
            "type": "string",
            "example": {
              "property_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          }
        ],
        "tags": [
          "Bills"
        ],
        "summary": "Obtener todas las facturas de una propiedad a partir de su property_id",
        "responses": {
          "200":{
            "example":[
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b",
                "property_id": "e1ac73f8-c39e6bbd523acc4b-b047-46bc",
                "monthly_paymment": 260,
                "debt": 940,
                "special_fee": 140,
                "other": 240,
                "creation_date": "Thu May 16 2019 13:43:13 GMT-0400 (GMT-04:00)",
                "last_update": "Thu May 16 2019 13:43:42 GMT-0400 (GMT-04:00)"
              }
            ]
          }
        }
      },
      "post": {
        "parameters": [
        {
          "name": "property_id",
          "in": "body",
          "required": true,
          "description": "id de la propiedad a la que se carga la factura",
          "type": "string",
          "example": {
            "property_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
          }
        },
        {
          "name": "monthly_payment",
          "in": "body",
          "required": true,
          "description": "Cantidad que el dueño de la propiedad pagara mensualmente",
          "type": "float",
          "example": {
            "monthly_paymment": 200
          }
        },
        {
          "name": "debt",
          "in": "body",
          "required": true,
          "description": "Deuda total del condominio",
          "type": "float",
          "example": {
            "debt": 2000
          }
        },
        {
          "name": "special_fee",
          "in": "body",
          "required": true,
          "description": "Cantidad para la cuota especial",
          "type": "float",
          "example": {
            "special_fee": 150
          }
        },
        {
          "name": "other",
          "in": "body",
          "required": true,
          "description": "Cantidad de algun otro gasto realizado",
          "type": "float",
          "example": {
            "other": 180
          }
        }
      ],
        "tags": [
          "Bills"
        ],
        "summary": "Crear una nueva factura",
        "responses": {
          "200": {
            "example": "Bill saved succesfully"
          }
        }
      },
      "put": {
        "parameters": [
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description": "id de la factura que se modificara",
            "type": "string",
            "example": {
              "property_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          },
          {
            "name": "property_id",
            "in": "body",
            "required": true,
            "description": "id de la propiedad a la que se carga la factura",
            "type": "string",
            "example": {
              "property_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          },
          {
            "name": "monthly_payment",
            "in": "body",
            "required": true,
            "description": "Cantidad que el dueño de la propiedad pagara mensualmente",
            "type": "float",
            "example": {
              "monthly_paymment": 200
            }
          },
          {
            "name": "debt",
            "in": "body",
            "required": true,
            "description": "Deuda total del condominio",
            "type": "float",
            "example": {
              "debt": 2000
            }
          },
          {
            "name": "special_fee",
            "in": "body",
            "required": true,
            "description": "Cantidad para la cuota especial",
            "type": "float",
            "example": {
              "special_fee": 150
            }
          },
          {
            "name": "other",
            "in": "body",
            "required": true,
            "description": "Cantidad de algun otro gasto realizado",
            "type": "float",
            "example": {
              "other": 180
            }
          }
        ],
        "tags": [
          "Bills"
        ],
        "summary": "Actualizar los datos de una factura (los únicos campos no actualizables son el id y la fecha de creacion)",
        "responses": {
          "200": {
            "example": "Property type updated succesfully"
          }
        }
      }
    },
    "/residency/create":{
      "post":{
        "parameters":[
          {
            "name": "admin_id",
            "in": "body",
            "required": true,
            "description":"id del administrador a cargo de esta residencia",
            "type": "string",
            "example":{
              "admin_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": true,
            "description": "Nombre de la residencia",
            "type": "string",
            "example": {
              "name": "Residencias Arivana"
            }
          },
          {
            "name": "yardage",
            "in": "body",
            "required": true,
            "description": "Espacio en yardas que ocupa la residencia",
            "type":"float",
            "example":{
                "yardage": 3000
            }
          }
        ],
        "tags":[
          "Residency"
        ],
        "summary": "Crear una nueva residencia",
        "responses":{
          "200":{
            "example":"Residency created succesfully"
          }
        }
      }
    },
    "/residency/residencies":{
      "get":{
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description":"id de la residencia a buscar",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          }
        ],
        "tags":[
          "Residency"
        ],
        "summary":"Obtener una residencia a partir de su id",
        "responses":{
          "200":{
            "example":[
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b",
                "admin_id": "6bbd523acc4a-b047-46bc-c39e-",
                "name": "Residencias Arivana",
                "yardage": 2000
              }
            ]
          }
        }
      }
    },
    "/residency/update":{
      "put":{
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description":"id de la residencia que sera actualizada",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name": "admin_id",
            "in": "body",
            "required": true,
            "description":"id del administrador a cargo de esta residencia",
            "type": "string",
            "example":{
              "admin_id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b"
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": true,
            "description": "Nombre de la residencia",
            "type": "string",
            "example": {
              "name": "Residencias Arivana"
            }
          },
          {
            "name": "yardage",
            "in": "body",
            "required": true,
            "description": "Espacio en yardas que ocupa la residencia",
            "type":"float",
            "example":{
                "yardage": 3000
            }
          }
        ],
        "tags":[
          "Residency"
        ],
        "summary": "Actualizar los datos de una residencia a partir de su id",
        "responses":{
          "200":{
            "example":"Residency updated succesfully"
          }
        }
      }
    },
    "/residency/expense":{
      "post":{
        "parameters":[
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description":"id del usuario responsable del gasto",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"amount",
            "in": "body",
            "required": true,
            "description": "Cantidad que el usuario va a pagar",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "concept",
            "in": "body",
            "required": true,
            "description": "Descripcion del gasto realizado",
            "type": "string",
            "example":{
              "concept": "Reparacion del porton principal"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Crear un nuevo gasto de la residencia",
        "responses":{
          "200":{
            "example":"Expense saved succesfully"
          }
        }
      },
      "get":{
        "parameters":[
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description": "id del usuario al que fueron cargados los gastos",
            "type": "string",
            "example":{
              "user_id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Obtener los gastos de un usuario a partir de su id",
        "responses":{
          "200":{
            "example":[
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b",
                "user_id": "e1ac73f8-c39e-46bc-b047-6bbd523lkD667",
                "amount": 3000,
                "concept": "Reparacion del motor del porton",
                "creation_date": "Fri May 24 2019 18:55:44 GMT-0400 (GMT-04:00)"
              }
            ]
          }
        }
      },
      "put":{
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description": "id del gasto que se modificara",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          },
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description":"id del usuario responsable del gasto",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"amount",
            "in": "body",
            "required": true,
            "description": "Cantidad que el usuario va a pagar",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "concept",
            "in": "body",
            "required": true,
            "description": "Descripcion del gasto realizado",
            "type": "string",
            "example":{
              "concept": "Reparacion del porton principal"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Actualizar un gasto a partir de su id",
        "responses":{
          "200":{
            "example": "Expense updated succesfully"
          }
        }
      }
    },
    "/residency/debts": {
      "get": {
        "parameters":[
          {
            "name": "residency_id",
            "in": "body",
            "required": true,
            "description": "id de la residencia de la cual queremos obtener las deudas",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          }
        ],
        "tags":["Residency"],
        "summary": "Obtener todas las deudas de una residencia, basado en el `residency_id`"
      }
    },
    "/residency/post": {
      "post": {
        "parameters": [
          {
            "name": "residency_id",
            "in": "body",
            "description": "id de la residencia",
            "type": "string",
            "example": {
              "residency_id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          },
          {
            "name": "user_id",
            "in": "body",
            "description": "id del usuario que publica",
            "type": "string",
            "example": {
              "user_id": "e1ac73f8-c39e-46bc-b047-asdfasdf"
            }
          },
          {
            "name": "content",
            "in": "body",
            "description": "contenido de la publicación",
            "type": "string",
            "example": {
              "content": "Mañana nos van a cortar el agua, tomen previsiones"
            }
          }
        ],
        "tags": ["Posts"],
        "summary": "Realizar una publicación al feed de la residencia"
      }
    },
    "/residency/feed": {
      "get": {
        "parameters": [
          {
            "name": "residency_id",
            "in": "body",
            "description": "id de la residencia",
            "type": "string",
            "example": {
              "residency_id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          }
        ],
        "tags": ["Posts"],
        "summary": "Obtener el feed de la residencia",
        "responses": {
          "200": {
            "description": "Retorna un array de posts, con el formato similar al del ejemplo",
            "example": "[\n  {\n    \"author\": \"Angel Rodríguez\",\n    \"content\": \"Nos van a cortar el agua manaure!\",\n    \"timestamp\": \"Hace 30 minutos\"\n  },\n  {\n    \"author\": \"Ricardo Castellanos\",\n    \"content\": \"Primero la gasolina, ahora esto...\",\n    \"timestamp\": \"Hace 25 minutos\"\n  }\n]"
          }
        }
      }
    },
    "/resident/debts": {
      "get": {
        "parameters":[
          {
            "name": "residency_id",
            "in": "body",
            "required": true,
            "description": "id de la propiedad del residente de la cual queremos obtener las deudas",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          }
        ],
        "tags": ["Resident"],
        "summary": "Obtener todas las deudas de una propiedad, basado en el `property_id`"
      }
    },
    "/resident/expense":{
      "post":{
        "parameters":[
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description":"id del usuario responsable del gasto",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"amount",
            "in": "body",
            "required": true,
            "description": "Cantidad que el usuario va a pagar",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "concept",
            "in": "body",
            "required": true,
            "description": "Descripcion del gasto realizado",
            "type": "string",
            "example":{
              "concept": "Reposicion de bombillos piso 5"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Crear un nuevo gasto de la residencia",
        "responses":{
          "200":{
            "example":"Expense saved succesfully"
          }
        }
      },
      "get":{
        "parameters":[
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description": "id del usuario al que fueron cargados los gastos",
            "type": "string",
            "example":{
              "user_id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Obtener los gastos de un usuario a partir de su id",
        "responses":{
          "200":{
            "example":[
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b",
                "user_id": "e1ac73f8-c39e-46bc-b047-6bbd523lkD667",
                "amount": 3000,
                "concept": "Reparacion tuberia Apto. 105",
                "creation_date": "Fri May 24 2019 18:55:44 GMT-0400 (GMT-04:00)"
              }
            ]
          }
        }
      },
      "put":{
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description": "id del gasto que se modificara",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          },
          {
            "name": "user_id",
            "in": "body",
            "required": true,
            "description":"id del usuario responsable del gasto",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"amount",
            "in": "body",
            "required": true,
            "description": "Cantidad que el usuario va a pagar",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "concept",
            "in": "body",
            "required": true,
            "description": "Descripcion del gasto realizado",
            "type": "string",
            "example":{
              "concept": "Reparacion del porton principal"
            }
          }
        ],
        "tags":[
          "Expenses"
        ],
        "summary": "Actualizar un gasto a partir de su id",
        "responses":{
          "200":{
            "example": "Expense updated succesfully"
          }
        }
      }
    },
    "/residency/service":{
      "post":{
        "parameters":[
          {
            "name": "residency_id",
            "in": "body",
            "required": true,
            "description":"id de la residencia a la que se presta el servicio",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"price",
            "in": "body",
            "required": true,
            "description": "Precio del servicio prestado",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": true,
            "description": "Nombre del servicio prestado",
            "type": "string",
            "example":{
              "concept": "Servicio de agua"
            }
          }
        ],
        "tags":[
          "Services"
        ],
        "summary": "Crear un nuevo servicio de la residencia",
        "responses":{
          "200":{
            "example":"Service saved succesfully"
          }
        }
      },
      "get":{
        "parameters":[
          {
            "name": "residency_id",
            "in": "body",
            "required": true,
            "description": "id de la residencia a la que se presta el servicio",
            "type": "string",
            "example":{
              "user_id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          }
        ],
        "tags":[
          "Services"
        ],
        "summary": "Obtener los servicios asociados a una residencia",
        "responses":{
          "200":{
            "example":[
              {
                "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b",
                "residency_id": "e1ac73f8-c39e-46bc-b047-6bbd523lkD667",
                "amount": 3000,
                "concept": "Servicio de luz"
              }
            ]
          }
        }
      },
      "put":{
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description": "id del servicio que se modificara",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          },
          {
            "name": "residency_id",
            "in": "body",
            "required": true,
            "description":"id de la residencia a la que se presta el servicio",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bbd523assd4b"
            }
          },
          {
            "name":"price",
            "in": "body",
            "required": true,
            "description": "Precio del servicio",
            "type": "float",
            "example":{
              "amount": 3000
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": true,
            "description": "Nombre del servicio que se presta",
            "type": "string",
            "example":{
              "concept": "Servicio de agua"
            }
          }
        ],
        "tags":[
          "Services"
        ],
        "summary": "Actualizar un servicio de la residencia a partir de su id",
        "responses":{
          "200":{
            "example": "Service updated succesfully"
          }
        }
      }
    },
    "/debts": {
      "put": {
        "parameters":[
          {
            "name": "id",
            "in": "body",
            "required": true,
            "description": "id de la deuda que queremos actualizar",
            "type": "string",
            "example":{
              "id": "e1ac73f8-c39e-46bc-b047-6bb558fgh456"
            }
          }
        ],
        "summary": "Actualizar el estado de una propiedad basado en el `id` de la deuda"
      }
    }
  },
  "definitions": {
    "Residency": {
      "required": [
        "id",
        "name",
        "yardage"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "yardage": {
          "type": "float"
        }
      }
    },
    "Service": {
      "required": [
        "id",
        "residency_id",
        "price",
        "name"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "residency_id": {
          "type": "string"
        },
        "price": {
          "type": "float"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Property Type": {
      "required": [
        "id",
        "residency_id",
        "name"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "residency_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "example": {
        "id": "e1ac73f8-c39e-46bc-b047-6bbd523acc4b",
        "residency_id": "6bbd523acc4b-c39e-46bc-b047-e1ac73f8",
        "name": "Penthouse"
       }
    },
    "Property Service": {
      "required": [
        "id",
        "service_id",
        "property_id"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "service_id": {
          "type": "string"
        },
        "property_id": {
          "type": "string"
        }
      }
    },
    "Property": {
      "required": [
        "id",
        "residency_id",
        "property_type_id",
        "user_id",
        "yardage",
        "department_number"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "residency_id": {
          "type": "string"
        },
        "property_type_id": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        },
        "yardage": {
          "type": "float"
        },
        "department_number": {
          "type": "string"
        }
      }
    },
    "User": {
      "required": [
        "id",
        "name",
        "lastname",
        "email",
        "social_number",
        "password"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "picture_url": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "social_number": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "Bill": {
      "required": [
        "id",
        "property_id",
        "amount",
        "description",
        "creation_date"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "property_id": {
          "type": "string"
        },
        "amount": {
          "type": "float"
        },
        "description": {
          "type": "string"
        },
        "creation_date": {
          "type": "timestamp"
        }
      }
    },
    "Debt": {
      "required": [
        "id",
        "property_id",
        "amount",
        "description",
        "creation_date"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "property_id": {
          "type": "string"
        },
        "amount": {
          "type": "float"
        },
        "description": {
          "type": "string"
        },
        "creation_date": {
          "type": "timestamp"
        }
      }
    },
    "Expense": {
      "required": [
        "id",
        "responsible_user_id",
        "amount",
        "concept",
        "creation_date"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "responsible_user_id": {
          "type": "string"
        },
        "amount": {
          "type": "float"
        },
        "concept": {
          "type": "string"
        },
        "creation_date": {
          "type": "timestamp"
        }
      }
    }
  }
}
